#convert -density 200x200 BON-scatter-QTL.eps BON-scatter-QTL.png
#convert -density 200x200 BON-scatter-FBE.eps BON-scatter-FBE.png
convert -density 200x200 BON-scatter-Temp.eps BON-scatter-Temp.png
#convert -density 200x200 IHR-scatter-QTL.eps IHR-scatter-QTL.png
#convert -density 200x200 IHR-scatter-FBE.eps IHR-scatter-FBE.png
convert -density 200x200 IHR-scatter-Temp.eps IHR-scatter-Temp.png
#convert -density 200x200 JDA-scatter-QTL.eps JDA-scatter-QTL.png
#convert -density 200x200 JDA-scatter-FBE.eps JDA-scatter-FBE.png
convert -density 200x200 JDA-scatter-Temp.eps JDA-scatter-Temp.png
#convert -density 200x200 LGS-scatter-QTL.eps LGS-scatter-QTL.png
#convert -density 200x200 LGS-scatter-FBE.eps LGS-scatter-FBE.png
convert -density 200x200 LGS-scatter-Temp.eps LGS-scatter-Temp.png
#convert -density 200x200 LMN-scatter-QTL.eps LMN-scatter-QTL.png
#convert -density 200x200 LMN-scatter-FBE.eps LMN-scatter-FBE.png
convert -density 200x200 LMN-scatter-Temp.eps LMN-scatter-Temp.png
#convert -density 200x200 LWG-scatter-QTL.eps LWG-scatter-QTL.png
#convert -density 200x200 LWG-scatter-FBE.eps LWG-scatter-FBE.png
convert -density 200x200 LWG-scatter-Temp.eps LWG-scatter-Temp.png
#convert -density 200x200 MCN-scatter-QTL.eps MCN-scatter-QTL.png
#convert -density 200x200 MCN-scatter-FBE.eps MCN-scatter-FBE.png
#convert -density 200x200 MCN-scatter-Temp.eps MCN-scatter-Temp.png
#convert -density 200x200 TDA-scatter-QTL.eps TDA-scatter-QTL.png
#convert -density 200x200 TDA-scatter-FBE.eps TDA-scatter-FBE.png
convert -density 200x200 TDA-scatter-Temp.eps TDA-scatter-Temp.png
convert -density 200x200 LEWI-scatter-Temp.eps LEWI-scatter-Temp.png
convert -density 200x200 SPALDING-scatter-Temp.eps SPALDING-scatter-Temp.png
convert -density 200x200 PEKI-scatter-Temp.eps PEKI-scatter-Temp.png
